### PR TITLE
Options for customizing build

### PR DESCRIPTION
**Pull request by croepha**
Please consider merging this.

While using this Docker setup, I have needed some customizations, and I modified the
Dockerfile and install.sh so that the image building can be customized in a number of
 ways without needing to fork.

Here are the added customizations:

```
--build-arg WITH_DEBUG=true  # Enables building nginx with debug, defaults to false
--build-arg WITH_LOADED_LIBAV=true  # Enables an alternative version of libav,
# that is newer and also supports libfdk-aac, defaults to false
--build-arg WITH_RTMP=false  # Enables the RTMP extension, defaults to true
--build-arg WITH_PAGESPEED=false # Enables Pagespeed, defaults to true
```

Here are some examples:

```

docker build -t docker-nginx .

$ docker run --rm -it docker-nginx nginx -V
Starting nginx...
nginx version: nginx/1.8.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf
--sbin-path=/usr/sbin --http-log-path=/var/log/nginx/access.log
--error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock
--pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy
--http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi
 --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module
--with-http_realip_module --with-http_addition_module --with-http_dav_module
--with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module
--with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail
--with-mail_ssl_module --add-module=/var/cache/nginx/nginx-rtmp-module
--add-module=/var/cache/nginx/ngx_pagespeed


$ docker run --rm -it docker-nginx avconv -version
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
avconv 9.18-6:9.18-0ubuntu0.14.04.1
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 0 / 54. 35. 0
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1


$ docker build -t docker-nginx-minimal --build-arg WITH_RTMP=false --build-arg WITH_PAGESPEED=false .

$ docker run --rm -it docker-nginx-minimal nginx -V
Starting nginx...
nginx version: nginx/1.8.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf
 --sbin-path=/usr/sbin --http-log-path=/var/log/nginx/access.log
--error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock
--pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy
--http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi
--with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module
--with-http_realip_module --with-http_addition_module --with-http_dav_module
 --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module
--with-http_spdy_module --with-http_sub_module --with-http_xslt_module
--with-mail --with-mail_ssl_module

$ docker run --rm -it docker-nginx-minimal avconv -version
/sbin/entrypoint.sh: line 38: exec: avconv: not found


$ docker build -t docker-nginx-loaded-streaming-debug --build-arg WITH_DEBUG=true --build-arg WITH_LOADED_LIBAV=true --build-arg WITH_PAGESPEED=false .

$ docker run --rm -it docker-nginx-loaded-streaming-debug nginx -V
Starting nginx...
nginx version: nginx/1.8.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf
--sbin-path=/usr/sbin --http-log-path=/var/log/nginx/access.log
 --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock
--pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy
 --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi
 --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module
--with-http_realip_module --with-http_addition_module --with-http_dav_module
--with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module
--with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail
--with-mail_ssl_module --add-module=/var/cache/nginx/nginx-rtmp-module --with-debug


$ docker run --rm -it docker-nginx-loaded-streaming-debug avconv -version
avconv version 11.4, Copyright (c) 2000-2014 the Libav developers
  built on Feb  5 2016 03:38:39 with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
avconv 11.4
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0
[daveb@localhost work_dir]$


```

### CODE REVIEW

**Comment by croepha** [comment]
Is there anything further I can do to help get this merged? or do you not like my approach?

**Comment by toxster** [comment]
+1 for merging this.

**Comment by sameersbn** [comment]
Hi. Sorry did not find the time to review this. 
Will try to do it today. Thanks for the PR

**Comment by sameersbn** [comment]
Sorry for the delay. The PR has been merged with a minor change, `WITH_LOADED_LIBAV` is renamed to `BUILD_LIBAV`

**Comment by croepha** [comment]
Awesome! Thanks

**Pull request merged**
